ccflags-y += -Idrivers/media/platform/msm/camera
ccflags-y += -Idrivers/media/platform/msm/camera/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
